# Generated by Django 2.0.10 on 2019-09-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='ping_num',
            new_name='ping_id',
        ),
    ]
