# Generated by Django 2.0.10 on 2019-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_auto_20191026_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommentcount',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postreactcount',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostCommentCount',
        ),
        migrations.DeleteModel(
            name='PostReactCount',
        ),
    ]
