# Generated by Django 2.0.10 on 2020-02-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_auto_20191128_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ping_id',
            field=models.CharField(blank=True, default=None, max_length=34, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ping_text',
            field=models.TextField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
