# Generated by Django 2.0.10 on 2019-06-20 11:55

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_50', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=authapp.models.test_get_file_path)),
                ('file_300', models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to=authapp.models.test_get_file_path_50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
