# Generated by Django 2.0.10 on 2019-11-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20191101_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpasswordresettoken',
            old_name='uuid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='userprimaryemailauthtoken',
            old_name='uuid',
            new_name='uid',
        ),
    ]
