# Generated by Django 2.0.10 on 2019-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20191104_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfirebaseinstanceid',
            name='instance_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
