# Generated by Django 2.0.10 on 2020-02-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20200104_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='device_called',
        ),
    ]
